server:
  port: 8081
  servlet:
    context-path: /luckymoney

limit:
  minMoney: 0.01
  maxMoney: 999
  description: 最少发${limit.minMoney}元,最多发${limit.maxMoney}元
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:8889/luckymoney
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
